### ISSUE TITLE
v0.2 Directory dumped into namespace

### ISSUE THREAD

**Issue by bluong** [sebastian-lenz/typedoc#51] opened 2015-01-15 01:28 UTC
When I run typedoc from the v0.2 branch, the links and the filenames are prepended with seemingly the absolute path to the relevant html file

**Comment by sebastian-lenz** [comment] 2015-01-25 22:42
I cannot reproduce your issue, the file names look correct in my test cases. Could you give me an example which generated wrong filenames?

We'll add the module name to the filenames (that should have been also the case with version 0.1). Is it possible that the string you see appended to the filenames is caused by a module definition?

**Comment by bluong** [comment] 2015-01-28 20:43
So playing around with the typedoc configuration.  If I use '--mode file', then I get all the filenames all look fine.  If I use '--mode modules' then I get the absolute path to the modules I believe dumped into the filename.

At the very least, we probably want to use the relative path, so that my username isn't shown on each web page :)

**Comment by sebastian-lenz** [comment] 2015-01-28 22:25
This issue seems to be resolved by the bugfix in #54.

**Closed by sebastian-lenz** 2015-01-28 22:25 UTC
Labels: question
