### ISSUE TITLE
Absolute Path to module shown on each web page

### ISSUE THREAD

**Issue by bluong** [sebastian-lenz/typedoc#54] opened 2015-01-28 20:45 UTC
After generating all of the docs, it seems that the absolute path to the typings file is dumped onto the webpage.  This is really odd, since my username is shown on the docs...?

**Comment by sebastian-lenz** [comment] 2015-01-28 21:02
Is this a duplicate of #51?

As you've noted there, using <code>--mode file</code> should always produce valid file names as the file names will be generated solely of module names. When using <code>--mode modules</code> TypeDoc tries to find the longest common base path of all source files and strips that of the final file names. Does your project spawn across multiple drives or directories within your userfolder? Could you please provide the command line you used to launch TypeDoc?

**Comment by bluong** [comment] 2015-01-28 21:06
The project itself is in a single source directory.

./node_modules/typedoc/bin/typedoc --mode file --includeDeclarations typings/d3/d3.d.ts plottable.d.ts --theme _typedoc/themes/plottable --out docs/

**Comment by sebastian-lenz** [comment] 2015-01-28 21:12
Thanks, I'll clone https://github.com/palantir/plottable.git and will check into it.

**Comment by sebastian-lenz** [comment] 2015-01-28 21:44
I've just pushed a bugfix, could you replace typedoc.js with https://github.com/sebastian-lenz/typedoc/raw/master/bin/typedoc.js?

**Comment by bluong** [comment] 2015-01-28 21:56
Fixes the absolute path issue :+1:

**Comment by sebastian-lenz** [comment] 2015-01-28 22:00
:tada: Great, thank you for testing the fix!

The same component is also used when file paths so I guess this issue should also be resolved.

**Closed by sebastian-lenz** 2015-01-28 22:00 UTC
Labels: bug

**Comment by sebastian-lenz** [comment] 2015-01-28 22:26
v0.2.1 is on npm containing the fix.
